import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Lato } from 'next/font/google'
import Footer from '@/components/Footer/Footer'

const inter = Lato({ subsets: ['latin'] , weight : "400"})



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
